

    %load data
    fid = fopen(['./output/output',num2str(fnr),'.dat']); %file handle
    xc = fread(fid,[ny,nx],'double'); %cell x coordinate (m)
    yc = fread(fid,[ny,nx],'double'); %cell y coordinate (m)
    bed = fread(fid,[ny,nx],'double'); %bed elevation (m)
    ice = fread(fid,[ny,nx],'double'); %ice thickness (m)
    bslope = fread(fid,[ny,nx],'double'); %bed slope (-)
    hydro = fread(fid,[ny,nx],'int'); %hydrology flag (ad hoc)
    slidingslope = fread(fid,[ny,nx],'double'); %bed slope in direction of sliding (-)
    ssedi = fread(fid,[ny,nx],'double'); %surface sediment thickness (m) 
    bsedi = fread(fid,[ny,nx],'double'); %basal-ice sediment thickness (m)
    msedi = fread(fid,[ny,nx],'double'); %mid-ice sediment thickness (m)
    sN10 = fread(fid,[ny,nx],'double'); %CN parameter (ad hoc)
    particles = fread(fid,[ny,nx],'int'); %number of particles in cell
    sediment = fread(fid,[ny,nx],'double'); %sediment thickness (m)
    tn = fread(fid,[ny,nx],'double'); %ice pressure normal to bed (m)
    te = fread(fid,[ny,nx],'double'); %effective pressure (m)
    ts = fread(fid,[ny,nx],'double'); %basal shear stress (m)
    sliding = fread(fid,[ny,nx],'double'); %sliding speed (m/y)
    deformation = fread(fid,[ny,nx],'double'); %ice deformation speed (m/y)
    td2 = fread(fid,[ny,nx],'double'); %square of deviatoric stress (m2)
    bmelt = fread(fid,[ny,nx],'double'); %basal melting rate (m/y)
    quarrying = fread(fid,[ny,nx],'double'); %total quarrying (m)
    accrate = fread(fid,[ny,nx],'double'); %ice accumulation rate (m/y)
    massb = fread(fid,[ny,nx],'double'); %effective mass balance (m/y)
    oro = fread(fid,[ny,nx],'double'); %ad hoc
    precip = fread(fid,[ny,nx],'double'); %ad hoc
    weathering = fread(fid,[ny,nx],'double'); %total erosion by weathering (m)
    abrasion = fread(fid,[ny,nx],'double'); %total erosion by abrasion (m)
    isostasy = fread(fid,[ny,nx],'double'); %isostatic uplift/subsidence (m)
    periglacial = fread(fid,[ny,nx],'double'); %total erosion by frost scattering (m)
    Ts = fread(fid,[ny,nx],'double'); %surface temperature in cell (C)
    hillslope = fread(fid,[ny,nx],'double'); %total erosion by hillslope processes (m)
    Ta = fread(fid,[ny,nx],'double'); %Atmospheric temperature (C)
    Tb = fread(fid,[ny,nx],'double'); %Basal temperature (C)
    sfac = fread(fid,[ny,nx],'double'); %Sliding fraction (-)
    icemargin = fread(fid,[ny,nx],'int'); %ice margin flag
    Ac = fread(fid,[ny,nx],'double'); %Melt water channel crosssectional area (m2)
    Kgw = fread(fid,[ny,nx],'double'); %thickness of water sheet (m)
    qw = fread(fid,[ny,nx],'double'); %water flux (m2/s)
    afac = fread(fid,[ny,nx],'double'); %longitudinal stress (m)
    water = fread(fid,[ny,nx],'double'); %water input (m)
    Pw = fread(fid,[ny,nx],'double'); %water pressure (m)
    SLf = fread(fid,[ny,nx],'double'); %bed contact fraction (-)
    mw = fread(fid,[ny,nx],'double'); %ad hoc
    sxx = fread(fid,[ny,nx],'double'); %ad hoc
    sxy = fread(fid,[ny,nx],'double'); %ad hoc
    syy = fread(fid,[ny,nx],'double'); %ad hoc
    dsxxdx = fread(fid,[ny,nx],'double'); %ad hoc
    dsxydx = fread(fid,[ny,nx],'double'); %ad hoc
    dsyydx = fread(fid,[ny,nx],'double'); %ad hoc
    dsxxdy = fread(fid,[ny,nx],'double'); %ad hoc
    dsxydy = fread(fid,[ny,nx],'double'); %ad hoc
    dsyydy = fread(fid,[ny,nx],'double'); %ad hoc
    vx = fread(fid,[ny,nx+1],'double'); %x velocity (m/y)
    vy = fread(fid,[ny+1,nx],'double'); %y velocity (m/y)
    vxres = fread(fid,[ny,nx+1],'double'); %x velocity residual (m/y)
    vyres = fread(fid,[ny+1,nx],'double'); %y velocity residual (m/y)
    fclose(fid);
    sN10 = sN10./(ssedi + 1e-3);